
 Network pedrohsb-python_backend  Creating
 Network pedrohsb-python_backend  Created
 Container pedrohsb-python-api1-1  Creating
 Container pedrohsb-python-api2-1  Creating
 Container pedrohsb-python-api1-1  Created
 Container pedrohsb-python-api2-1  Created
 Container nginx1  Creating
 Container nginx1  Created
Attaching to nginx1, api1-1, api2-1
nginx1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx1  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
nginx1  | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx1  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx1  | /docker-entrypoint.sh: Configuration complete; ready for start up
api1-1  | INFO:     Started server process [1]
api1-1  | INFO:     Waiting for application startup.
api2-1  | INFO:     Started server process [1]
api2-1  | INFO:     Waiting for application startup.
api2-1  | INFO:     Application startup complete.
api1-1  | INFO:     Application startup complete.
api1-1  | INFO:     Uvicorn running on http://0.0.0.0:9999 (Press CTRL+C to quit)
api2-1  | INFO:     Uvicorn running on http://0.0.0.0:9999 (Press CTRL+C to quit)
[Knginx1 exited with code 0
api2-1  | INFO:     Shutting down
api1-1  | INFO:     Shutting down
api2-1  | INFO:     Waiting for application shutdown.
api2-1  | INFO:     Application shutdown complete.
api2-1  | INFO:     Finished server process [1]
api2-1  | _GatheringFuture exception was never retrieved
api2-1  | future: <_GatheringFuture finished exception=CancelledError()>
api2-1  | Traceback (most recent call last):
api2-1  |   File "/app/app/worker.py", line 54, in worker
api2-1  |     ok = await process_payment(
api2-1  |          ^^^^^^^^^^^^^^^^^^^^^^
api2-1  |     ...<4 lines>...
api2-1  |     )
api2-1  |     ^
api2-1  |   File "/app/app/worker.py", line 67, in process_payment
api2-1  |     processor, ok = await post_payment(payload, url, processor, requested_at)
api2-1  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |   File "/app/app/worker.py", line 39, in post_payment
api2-1  |     res = await client.post(
api2-1  |           ^^^^^^^^^^^^^^^^^^
api2-1  |     ...<2 lines>...
api2-1  |     )
api2-1  |     ^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1859, in post
api2-1  |     return await self.request(
api2-1  |            ^^^^^^^^^^^^^^^^^^^
api2-1  |     ...<13 lines>...
api2-1  |     )
api2-1  |     ^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1540, in request
api2-1  |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)
api2-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1629, in send
api2-1  |     response = await self._send_handling_auth(
api2-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |     ...<4 lines>...
api2-1  |     )
api2-1  |     ^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1657, in _send_handling_auth
api2-1  |     response = await self._send_handling_redirects(
api2-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |     ...<3 lines>...
api2-1  |     )
api2-1  |     ^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1694, in _send_handling_redirects
api2-1  |     response = await self._send_single_request(request)
api2-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1730, in _send_single_request
api2-1  |     response = await transport.handle_async_request(request)
api2-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py", line 394, in handle_async_request
api2-1  |     resp = await self._pool.handle_async_request(req)
api2-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpcore/_async/connection_pool.py", line 256, in handle_async_request
api2-1  |     raise exc from None
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpcore/_async/connection_pool.py", line 236, in handle_async_request
api2-1  |     response = await connection.handle_async_request(
api2-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |         pool_request.request
api2-1  |         ^^^^^^^^^^^^^^^^^^^^
api2-1  |     )
api2-1  |     ^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpcore/_async/connection.py", line 103, in handle_async_request
api2-1  |     return await self._connection.handle_async_request(request)
api2-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpcore/_async/http11.py", line 136, in handle_async_request
api2-1  |     raise exc
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpcore/_async/http11.py", line 106, in handle_async_request
api2-1  |     ) = await self._receive_response_headers(**kwargs)
api2-1  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpcore/_async/http11.py", line 177, in _receive_response_headers
api2-1  |     event = await self._receive_event(timeout=timeout)
api2-1  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpcore/_async/http11.py", line 217, in _receive_event
api2-1  |     data = await self._network_stream.read(
api2-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |         self.READ_NUM_BYTES, timeout=timeout
api2-1  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |     )
api2-1  |     ^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpcore/_backends/anyio.py", line 35, in read
api2-1  |     return await self._stream.receive(max_bytes=max_bytes)
api2-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/anyio/_backends/_asyncio.py", line 1254, in receive
api2-1  |     await self._protocol.read_event.wait()
api2-1  |   File "/usr/local/lib/python3.13/asyncio/locks.py", line 213, in wait
api2-1  |     await fut
api2-1  | asyncio.exceptions.CancelledError
api1-1  | INFO:     Waiting for application shutdown.
api1-1  | INFO:     Application shutdown complete.
api1-1  | INFO:     Finished server process [1]
api1-1  | _GatheringFuture exception was never retrieved
api1-1  | future: <_GatheringFuture finished exception=CancelledError()>
api1-1  | Traceback (most recent call last):
api1-1  |   File "/app/app/worker.py", line 54, in worker
api1-1  |     ok = await process_payment(
api1-1  |          ^^^^^^^^^^^^^^^^^^^^^^
api1-1  |     ...<4 lines>...
api1-1  |     )
api1-1  |     ^
api1-1  |   File "/app/app/worker.py", line 67, in process_payment
api1-1  |     processor, ok = await post_payment(payload, url, processor, requested_at)
api1-1  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |   File "/app/app/worker.py", line 39, in post_payment
api1-1  |     res = await client.post(
api1-1  |           ^^^^^^^^^^^^^^^^^^
api1-1  |     ...<2 lines>...
api1-1  |     )
api1-1  |     ^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1859, in post
api1-1  |     return await self.request(
api1-1  |            ^^^^^^^^^^^^^^^^^^^
api1-1  |     ...<13 lines>...
api1-1  |     )
api1-1  |     ^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1540, in request
api1-1  |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)
api1-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1629, in send
api1-1  |     response = await self._send_handling_auth(
api1-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |     ...<4 lines>...
api1-1  |     )
api1-1  |     ^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1657, in _send_handling_auth
api1-1  |     response = await self._send_handling_redirects(
api1-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |     ...<3 lines>...
api1-1  |     )
api1-1  |     ^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1694, in _send_handling_redirects
api1-1  |     response = await self._send_single_request(request)
api1-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1730, in _send_single_request
api1-1  |     response = await transport.handle_async_request(request)
api1-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py", line 394, in handle_async_request
api1-1  |     resp = await self._pool.handle_async_request(req)
api1-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpcore/_async/connection_pool.py", line 256, in handle_async_request
api1-1  |     raise exc from None
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpcore/_async/connection_pool.py", line 236, in handle_async_request
api1-1  |     response = await connection.handle_async_request(
api1-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |         pool_request.request
api1-1  |         ^^^^^^^^^^^^^^^^^^^^
api1-1  |     )
api1-1  |     ^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpcore/_async/connection.py", line 103, in handle_async_request
api1-1  |     return await self._connection.handle_async_request(request)
api1-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpcore/_async/http11.py", line 136, in handle_async_request
api1-1  |     raise exc
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpcore/_async/http11.py", line 106, in handle_async_request
api1-1  |     ) = await self._receive_response_headers(**kwargs)
api1-1  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpcore/_async/http11.py", line 177, in _receive_response_headers
api1-1  |     event = await self._receive_event(timeout=timeout)
api1-1  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpcore/_async/http11.py", line 217, in _receive_event
api1-1  |     data = await self._network_stream.read(
api1-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |         self.READ_NUM_BYTES, timeout=timeout
api1-1  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |     )
api1-1  |     ^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpcore/_backends/anyio.py", line 35, in read
api1-1  |     return await self._stream.receive(max_bytes=max_bytes)
api1-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/anyio/_backends/_asyncio.py", line 1254, in receive
api1-1  |     await self._protocol.read_event.wait()
api1-1  |   File "/usr/local/lib/python3.13/asyncio/locks.py", line 213, in wait
api1-1  |     await fut
api1-1  | asyncio.exceptions.CancelledError
log truncated at line 1000
