
 Network patrignani-go_rinha-back  Creating
 Network patrignani-go_rinha-back  Created
 Volume "patrignani-go_pgdata"  Creating
 Volume "patrignani-go_pgdata"  Created
 Container patrignani-go-db-1  Creating
 Container patrignani-go-db-1  Created
 Container api2  Creating
 Container api1  Creating
 Container api2  Created
 Container api1  Created
 Container haproxy-lb  Creating
 Container haproxy-lb  Created
Attaching to api1, api2, haproxy-lb, db-1
db-1  | The files belonging to this database system will be owned by user "postgres".
db-1  | This user must also own the server process.
db-1  | 
db-1  | The database cluster will be initialized with locale "en_US.utf8".
db-1  | The default database encoding has accordingly been set to "UTF8".
db-1  | The default text search configuration will be set to "english".
db-1  | 
db-1  | Data page checksums are disabled.
db-1  | 
db-1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db-1  | creating subdirectories ... ok
db-1  | selecting dynamic shared memory implementation ... posix
db-1  | selecting default "max_connections" ... 100
db-1  | selecting default "shared_buffers" ... 128MB
api1  | 2025/08/19 12:22:18 ____queue.Send____
api1  | 2025/08/19 12:22:18 
api1  | 	╔════════════════════════════════════════════════════╗
api1  | 	║ 🚀 Servidor iniciado com sucesso!                   ║
api1  | 	║ 📡 Escutando em: http://:8080                          ║
api1  | 	╚════════════════════════════════════════════════════╝
api1  | 	
api1  | [gnet] 2025-08-19T12:22:18.811794671Z	INFO	logging/logger.go:256	Launching gnet with 4 event-loops, listening on: tcp://:8080
api2  | 2025/08/19 12:22:18 ____queue.Send____
api2  | 2025/08/19 12:22:18 
api2  | 	╔════════════════════════════════════════════════════╗
api2  | 	║ 🚀 Servidor iniciado com sucesso!                   ║
api2  | 	║ 📡 Escutando em: http://:8080                          ║
api2  | 	╚════════════════════════════════════════════════════╝
api2  | 	
api1  | 2025/08/19 12:22:18 [Retry] Worker iniciado (intervalo: 300ms)
api2  | 2025/08/19 12:22:18 [Retry] Worker iniciado (intervalo: 300ms)
api2  | [gnet] 2025-08-19T12:22:18.812952068Z	INFO	logging/logger.go:256	Launching gnet with 4 event-loops, listening on: tcp://:8080
db-1  | selecting default time zone ... UTC
db-1  | creating configuration files ... ok
haproxy-lb  | [NOTICE]   (1) : New worker (8) forked
haproxy-lb  | [NOTICE]   (1) : Loading success.
db-1        | running bootstrap script ... ok
db-1        | sh: locale: not found
db-1        | 2025-08-19 12:22:21.335 UTC [34] WARNING:  no usable system locales were found
db-1        | performing post-bootstrap initialization ... ok
db-1        | initdb: warning: enabling "trust" authentication for local connections
db-1        | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
db-1        | syncing data to disk ... ok
db-1        | 
db-1        | 
db-1        | Success. You can now start the database server using:
db-1        | 
db-1        |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db-1        | 
db-1        | waiting for server to start....2025-08-19 12:22:23.364 UTC [40] LOG:  starting PostgreSQL 17.5 on x86_64-pc-linux-musl, compiled by gcc (Alpine 14.2.0) 14.2.0, 64-bit
db-1        | 2025-08-19 12:22:23.364 UTC [40] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1        | 2025-08-19 12:22:23.435 UTC [43] LOG:  database system was shut down at 2025-08-19 12:22:23 UTC
db-1        | 2025-08-19 12:22:23.440 UTC [40] LOG:  database system is ready to accept connections
db-1        |  done
db-1        | server started
db-1        | CREATE DATABASE
db-1        | 
db-1        | 
db-1        | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/payment.sql
db-1        | CREATE TABLE
db-1        | CREATE INDEX
db-1        | 
db-1        | 
db-1        | waiting for server to shut down....2025-08-19 12:22:23.751 UTC [40] LOG:  received fast shutdown request
db-1        | 2025-08-19 12:22:23.751 UTC [40] LOG:  aborting any active transactions
db-1        | 2025-08-19 12:22:23.754 UTC [40] LOG:  background worker "logical replication launcher" (PID 46) exited with exit code 1
db-1        | 2025-08-19 12:22:23.835 UTC [41] LOG:  shutting down
db-1        | 2025-08-19 12:22:23.835 UTC [41] LOG:  checkpoint starting: shutdown immediate
db-1        | 2025-08-19 12:22:23.844 UTC [41] LOG:  checkpoint complete: wrote 930 buffers (22.7%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.009 s, sync=0.001 s, total=0.010 s; sync files=0, longest=0.000 s, average=0.000 s; distance=4276 kB, estimate=4276 kB; lsn=0/191A390, redo lsn=0/191A390
db-1        | 2025-08-19 12:22:23.852 UTC [40] LOG:  database system is shut down
db-1        |  done
db-1        | server stopped
db-1        | 
db-1        | PostgreSQL init process complete; ready for start up.
db-1        | 
db-1        | 2025-08-19 12:22:23.967 UTC [1] LOG:  starting PostgreSQL 17.5 on x86_64-pc-linux-musl, compiled by gcc (Alpine 14.2.0) 14.2.0, 64-bit
db-1        | 2025-08-19 12:22:23.967 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db-1        | 2025-08-19 12:22:23.967 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db-1        | 2025-08-19 12:22:23.967 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1        | 2025-08-19 12:22:23.969 UTC [58] LOG:  database system was shut down at 2025-08-19 12:22:23 UTC
db-1        | 2025-08-19 12:22:23.974 UTC [1] LOG:  database system is ready to accept connections
api2        | Erro ao processar mensagem cannot parse JSON: cannot parse number: unexpected char: "k"; unparsed tail: "k6/1.1.0\r\nContent-Type: application/json\r\n\r\nf58caf3a9\",\"amount\":20.05}"
api2        | Erro ao processar mensagem cannot parse JSON: cannot parse number: unexpected char: "k"; unparsed tail: "k6/1.1.0\r\nContent-Type: application/json\r\n\r\nf58caf3a9\",\"amount\":20.05}"
api2        | ERRO DE CONVERSÃO cannot parse JSON: cannot parse number: unexpected char: "k"; unparsed tail: "k6/1.1.0\r\nContent-Type: application/json\r\n\r\nf58caf3a9\",\"amount\":20.05}"
api2        | ERRO DE CONVERSÃO cannot parse JSON: cannot parse number: unexpected char: "k"; unparsed tail: "k6/1.1.0\r\nContent-Type: application/json\r\n\r\nf58caf3a9\",\"amount\":20.05}"
db-1        | 2025-08-19 12:24:04.302 UTC [74] ERROR:  duplicate key value violates unique constraint "entry_history_pkey"
db-1        | 2025-08-19 12:24:04.302 UTC [74] DETAIL:  Key (correlationid)=(dd292c71-6e7d-4d9a-a183-4c9cdcc9762f) already exists.
db-1        | 2025-08-19 12:24:04.302 UTC [74] STATEMENT:  
db-1        | 			INSERT INTO entry_history (correlationId, amount, fallback, created_at)
db-1        | 			VALUES ($1, $2, $3, $4)
db-1        | 		
db-1        | 2025-08-19 12:24:04.305 UTC [74] ERROR:  duplicate key value violates unique constraint "entry_history_pkey"
db-1        | 2025-08-19 12:24:04.305 UTC [74] DETAIL:  Key (correlationid)=(97f90384-71a0-4731-a018-3924c911eeda) already exists.
db-1        | 2025-08-19 12:24:04.305 UTC [74] STATEMENT:  
db-1        | 			INSERT INTO entry_history (correlationId, amount, fallback, created_at)
db-1        | 			VALUES ($1, $2, $3, $4)
db-1        | 		
db-1        | 2025-08-19 12:24:04.308 UTC [74] ERROR:  duplicate key value violates unique constraint "entry_history_pkey"
db-1        | 2025-08-19 12:24:04.308 UTC [74] DETAIL:  Key (correlationid)=(fe4912ad-b1cb-497f-867b-81f9dcee43d3) already exists.
db-1        | 2025-08-19 12:24:04.308 UTC [74] STATEMENT:  
db-1        | 			INSERT INTO entry_history (correlationId, amount, fallback, created_at)
db-1        | 			VALUES ($1, $2, $3, $4)
db-1        | 		
db-1        | 2025-08-19 12:24:04.313 UTC [74] ERROR:  duplicate key value violates unique constraint "entry_history_pkey"
db-1        | 2025-08-19 12:24:04.313 UTC [74] DETAIL:  Key (correlationid)=(be387904-8253-4937-90d7-674726e5bd8e) already exists.
db-1        | 2025-08-19 12:24:04.313 UTC [74] STATEMENT:  
db-1        | 			INSERT INTO entry_history (correlationId, amount, fallback, created_at)
db-1        | 			VALUES ($1, $2, $3, $4)
db-1        | 		
api2        | Erro ao processar mensagem cannot parse JSON: cannot parse number: unexpected char: "k"; unparsed tail: "k6/1.1.0\r\nContent-Type: application/json\r\n\r\n8230273e1\",\"amount\":20.05}"
api2        | ERRO DE CONVERSÃO cannot parse JSON: cannot parse number: unexpected char: "k"; unparsed tail: "k6/1.1.0\r\nContent-Type: application/json\r\n\r\n8230273e1\",\"amount\":20.05}"
api2        | ERRO DE CONVERSÃO cannot parse JSON: cannot parse number: unexpected char: "k"; unparsed tail: "k6/1.1.0\r\nContent-Type: application/json\r\n\r\n8230273e1\",\"amount\":20.05}"
api2        | Erro ao processar mensagem cannot parse JSON: cannot parse number: unexpected char: "k"; unparsed tail: "k6/1.1.0\r\nContent-Type: application/json\r\n\r\n8230273e1\",\"amount\":20.05}"
api2        | ERRO DE CONVERSÃO cannot parse JSON: cannot parse number: unexpected char: "k"; unparsed tail: "k6/1.1.0\r\nContent-Type: application/json\r\n\r\na1afd4a70\",\"amount\":20.05}"
api2        | ERRO DE CONVERSÃO cannot parse JSON: cannot parse number: unexpected char: "k"; unparsed tail: "k6/1.1.0\r\nContent-Type: application/json\r\n\r\na1afd4a70\",\"amount\":20.05}"
api2        | Erro ao processar mensagem cannot parse JSON: cannot parse number: unexpected char: "k"; unparsed tail: "k6/1.1.0\r\nContent-Type: application/json\r\n\r\na1afd4a70\",\"amount\":20.05}"
api2        | Erro ao processar mensagem cannot parse JSON: cannot parse number: unexpected char: "k"; unparsed tail: "k6/1.1.0\r\nContent-Type: application/json\r\n\r\na1afd4a70\",\"amount\":20.05}"
api2        | ERRO DE CONVERSÃO cannot parse JSON: cannot parse number: unexpected char: "k"; unparsed tail: "k6/1.1.0\r\nContent-Type: application/json\r\n\r\na1afd4a70\",\"amount\":20.05}"
api2        | Erro ao processar mensagem cannot parse JSON: cannot parse number: unexpected char: "k"; unparsed tail: "k6/1.1.0\r\nContent-Type: application/json\r\n\r\na1afd4a70\",\"amount\":20.05}"
api2        | ERRO DE CONVERSÃO cannot parse JSON: cannot parse number: unexpected char: "k"; unparsed tail: "k6/1.1.0\r\nContent-Type: application/json\r\n\r\n51c4a2639\",\"amount\":20.05}"
api2        | Erro ao processar mensagem cannot parse JSON: cannot parse number: unexpected char: "k"; unparsed tail: "k6/1.1.0\r\nContent-Type: application/json\r\n\r\n51c4a2639\",\"amount\":20.05}"
api2        | Erro ao processar mensagem cannot parse JSON: cannot parse number: unexpected char: "k"; unparsed tail: "k6/1.1.0\r\nContent-Type: application/json\r\n\r\nded1ab786\",\"amount\":20.05}"
api2        | ERRO DE CONVERSÃO cannot parse JSON: cannot parse number: unexpected char: "k"; unparsed tail: "k6/1.1.0\r\nContent-Type: application/json\r\n\r\nded1ab786\",\"amount\":20.05}"
api2        | Erro ao processar mensagem cannot parse JSON: cannot parse number: unexpected char: "k"; unparsed tail: "k6/1.1.0\r\nContent-Type: application/json\r\n\r\n8e18c878a\",\"amount\":20.05}"
api2        | ERRO DE CONVERSÃO cannot parse JSON: cannot parse number: unexpected char: "k"; unparsed tail: "k6/1.1.0\r\nContent-Type: application/json\r\n\r\n8e18c878a\",\"amount\":20.05}"
api2        | ERRO DE CONVERSÃO cannot parse JSON: cannot parse number: unexpected char: "k"; unparsed tail: "k6/1.1.0\r\nContent-Type: application/json\r\n\r\n96d2231ff\",\"amount\":20.05}"
api2        | Erro ao processar mensagem cannot parse JSON: cannot parse number: unexpected char: "k"; unparsed tail: "k6/1.1.0\r\nContent-Type: application/json\r\n\r\n96d2231ff\",\"amount\":20.05}"
api2        | Erro ao processar mensagem cannot parse JSON: cannot parse number: unexpected char: "k"; unparsed tail: "k6/1.1.0\r\nContent-Type: application/json\r\n\r\n96d2231ff\",\"amount\":20.05}"
api2        | Erro ao processar mensagem cannot parse JSON: cannot parse number: unexpected char: "k"; unparsed tail: "k6/1.1.0\r\nContent-Type: application/json\r\n\r\n96d2231ff\",\"amount\":20.05}"
api2        | Erro ao processar mensagem cannot parse JSON: cannot parse number: unexpected char: "k"; unparsed tail: "k6/1.1.0\r\nContent-Type: application/json\r\n\r\n96d2231ff\",\"amount\":20.05}"
api2        | ERRO DE CONVERSÃO cannot parse JSON: cannot parse number: unexpected char: "k"; unparsed tail: "k6/1.1.0\r\nContent-Type: application/json\r\n\r\n96d2231ff\",\"amount\":20.05}"
api2        | ERRO DE CONVERSÃO cannot parse JSON: cannot parse number: unexpected char: "k"; unparsed tail: "k6/1.1.0\r\nContent-Type: application/json\r\n\r\n96d2231ff\",\"amount\":20.05}"
api2        | ERRO DE CONVERSÃO cannot parse JSON: cannot parse number: unexpected char: "k"; unparsed tail: "k6/1.1.0\r\nContent-Type: application/json\r\n\r\n96d2231ff\",\"amount\":20.05}"
api2        | ERRO DE CONVERSÃO cannot parse JSON: cannot parse number: unexpected char: "k"; unparsed tail: "k6/1.1.0\r\nContent-Type: application/json\r\n\r\na748b0810\",\"amount\":20.05}"
api2        | Erro ao processar mensagem cannot parse JSON: cannot parse number: unexpected char: "k"; unparsed tail: "k6/1.1.0\r\nContent-Type: application/json\r\n\r\na748b0810\",\"amount\":20.05}"
api2        | ERRO DE CONVERSÃO cannot parse JSON: cannot parse number: unexpected char: "k"; unparsed tail: "k6/1.1.0\r\nContent-Type: application/json\r\n\r\nb6c3193d9\",\"amount\":20.05}"
api2        | Erro ao processar mensagem cannot parse JSON: cannot parse number: unexpected char: "k"; unparsed tail: "k6/1.1.0\r\nContent-Type: application/json\r\n\r\nb6c3193d9\",\"amount\":20.05}"
db-1        | 2025-08-19 12:27:24.049 UTC [56] LOG:  checkpoint starting: time
db-1        | 2025-08-19 12:27:28.858 UTC [56] LOG:  checkpoint complete: wrote 67 buffers (1.6%); 0 WAL file(s) added, 0 removed, 0 recycled; write=4.809 s, sync=0.001 s, total=4.809 s; sync files=0, longest=0.000 s, average=0.000 s; distance=1605 kB, estimate=1605 kB; lsn=0/1AAC360, redo lsn=0/1AAB990
haproxy-lb  | [NOTICE]   (1) : haproxy version is 2.9.15-e872a3f
haproxy-lb  | [WARNING]  (1) : Exiting Master process...
haproxy-lb  | [WARNING]  (8) : Proxy pay_front stopped (cumulated conns: FE: 606, BE: 0).
haproxy-lb  | [WARNING]  (8) : Proxy pay_api stopped (cumulated conns: FE: 0, BE: 606).
haproxy-lb  | [WARNING]  (1) : Current worker (8) exited with code 0 (Exit)
haproxy-lb  | [WARNING]  (1) : All workers exited. Exiting... (0)
[Khaproxy-lb exited with code 0
[Kapi1 exited with code 2
[Kapi2 exited with code 2
db-1        | 2025-08-19 12:27:35.277 UTC [1] LOG:  received fast shutdown request
db-1        | 2025-08-19 12:27:35.277 UTC [1] LOG:  aborting any active transactions
db-1        | 2025-08-19 12:27:35.281 UTC [1] LOG:  background worker "logical replication launcher" (PID 61) exited with exit code 1
db-1        | 2025-08-19 12:27:35.281 UTC [56] LOG:  shutting down
db-1        | 2025-08-19 12:27:35.281 UTC [56] LOG:  checkpoint starting: shutdown immediate
db-1        | 2025-08-19 12:27:35.285 UTC [56] LOG:  checkpoint complete: wrote 590 buffers (14.4%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.003 s, sync=0.001 s, total=0.004 s; sync files=0, longest=0.000 s, average=0.000 s; distance=5 kB, estimate=1445 kB; lsn=0/1AACFE0, redo lsn=0/1AACFE0
db-1        | 2025-08-19 12:27:35.291 UTC [1] LOG:  database system is shut down
log truncated at line 1000
